//! Tree-structured session persistence with pluggable backends.

pub mod backends;
pub mod context;
pub mod id;
pub mod migrations;
pub mod repo;
pub mod repo_utils;
pub mod storage_utils;
pub mod tree;
pub mod types;

pub use backends::InMemorySessionOptions;
pub use backends::InMemorySessionStorage;
pub use backends::SessionDirCreateOptions;
pub use backends::SessionDirStorage;
pub use backends::TursoSessionStorage;
pub use backends::load_session_metadata;
pub use backends::session_dir::{EVENTS_FILE, SUMMARY_FILE};
pub use context::build_context_entries;
pub use context::build_session_context;
pub use context::build_session_context_with_options;
pub use context::default_context_entry_transform;
pub use context::{ContextEntryTransform, CustomEntryContextMessageProjector, SessionContextBuildOptions};
pub use migrations::SESSION_TREE_MIGRATIONS;
pub use repo::InMemorySessionCreateOptions;
pub use repo::InMemorySessionRepo;
pub use repo::SessionDirListOptions;
pub use repo::SessionDirRepo;
pub use repo::SessionDirRepoCreateOptions;
pub use repo_utils::{ForkEntriesOptions, ForkPosition};
pub use repo_utils::{create_session_id, create_timestamp, get_entries_to_fork, to_session};
pub use tree::{BranchSummaryOptions, Session};
pub use types::CustomMessageEntryBlock;
pub use types::CustomMessageEntryContent;
pub use types::SessionContext;
pub use types::SessionDirMetadata;
pub use types::SessionError;
pub use types::SessionErrorCode;
pub use types::SessionMetadata;
pub use types::SessionModelRef;
pub use types::SessionStorage;
pub use types::SessionTreeEntry;
pub use types::TursoSessionMetadata;
