# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# git tag --delete elph-v0.0.1
# git push origin --delete tag elph-v0.0.1
# git tag elph-v0.0.1 -m "version bump"
# git push origin elph-v0.0.1

name: Release Elph

on:
  push:
    tags: ["elph-v*.*.*"]

permissions:
  contents: write

concurrency:
  group: release-elph-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/_release-app.yml
    with:
      app: elph
