# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# git tag --delete owly-v0.0.1
# git push origin --delete tag owly-v0.0.1
# git tag owly-v0.0.1 -m "version bump"
# git push origin owly-v0.0.1

name: Release Owly

on:
  push:
    tags: ["owly-v*.*.*"]

permissions:
  contents: write

concurrency:
  group: release-owly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/_release-app.yml
    with:
      app: owly
